trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  GITHUB_USERNAME: 'LaylaLiu-gmail'
  GITHUB_REPO: 'layliunode14git'    # The GitHub repository name (e.g., 'my-repo')

steps:
- script: |
    git config --global user.name 'azure-devops'
    git config --global user.email 'azure-devops@devops.com'

    cd $(Build.SourcesDirectory)
    git log
    git remote add github https://$(GITHUB_TOKEN)@github.com/LaylaLiu-gmail/layliunode14git.git
    git remote -v
    git push github --tags "refs/remotes/origin/*:refs/heads/*"
    git branch --all
    git push github --tags
    git branch --all
  displayName: 'Push to GitHub'