trigger:
- none

pool:
  vmImage: 'windows-latest'

resources:
  repositories:
    - repository: githubRepo
      type: github
      name: LaylaLiu-gmail/layliunode14git
      endpoint: github-LaylaLiu-gmail

steps:
- script: |
    git config --global user.name 'azure-devops'
    git config --global user.email 'azure-devops@devops.com'
  displayName: 'Set up Git'

- script: |
    cd $(Build.SourcesDirectory)
    git remote add github https://github.com/LaylaLiu-gmail/layliunode14git.git
    git push github --all
    git push github --tags
  displayName: 'Push to GitHub'
  env:
    GIT_ASKPASS: echo
    GIT_TERMINAL_PROMPT: 0